version: "3.7"

networks:
  outside:
    name: sentry-self-hosted_default
    external: true
  self:
    name: events

volumes:
  postgres-data:
  postgres-data2:

services:
  
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: meta2
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./data/postgres/backup:/backup
    networks:
      - self

  postgres-payment:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: meta2
    volumes:
      - postgres-data2:/var/lib/postgresql/data
      - ./data/postgres/backup:/backup
    networks:
      - self

  rabbitmq:
    image: "rabbitmq:management-alpine"
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"  # RabbitMQ Management UI
    networks:
      - self


  main:
    restart: unless-stopped
    build:
      context: ./orders
      dockerfile: .Dockerfile
    env_file:
      - ./orders/.env
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - self
      - outside

  notify:
    restart: unless-stopped
    build:
      context: ./event-notify
      dockerfile: .Dockerfile
    env_file:
      - ./event-notify/.env
    depends_on:
      - rabbitmq
    networks:
      - self
      - outside

  payment:
    restart: unless-stopped
    build:
      context: ./event-payment-service
      dockerfile: .Dockerfile
    env_file:
      - ./event-payment-service/.env
    depends_on:
      - rabbitmq
      - postgres-payment
    networks:
      - self
      - outside